apiVersion: v1
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      namespace: rhoai-model-registries
      labels:
        app.kubernetes.io/name: model-registry-db
        app.kubernetes.io/instance: model-registry-db
        app.kubernetes.io/part-of: model-registry-db
        app.kubernetes.io/managed-by: kustomize
      annotations:
        template.openshift.io/expose-database_name: '{.data[''database-name'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-username: '{.data[''database-user'']}'
      name: model-registry-db
    stringData:
      database-name: model_registry
      database-password: TheBlurstOfTimes
      database-user: modelregistryuser
  - apiVersion: modelregistry.opendatahub.io/v1alpha1
    kind: ModelRegistry
    metadata:
      labels:
        app.kubernetes.io/created-by: model-registry-operator
        app.kubernetes.io/instance: modelregistry-sample
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: modelregistry
        app.kubernetes.io/part-of: model-registry-operator
      name: modelregistry-public
      namespace: rhoai-model-registries
    spec:
      rest: {}
      istio:
        authProvider: opendatahub-auth-provider
        gateway:
          rest:
            tls: {}
      mysql:
        host: model-registry-db.test-db.svc.cluster.local
        database: model_registry
        passwordSecret:
          key: database-password
          name: model-registry-db
        port: 3306
        skipDBCreation: false
        username: modelregistryuser
kind: List
metadata: {}